import React, { useState, useEffect, useCallback } from 'react';
import { BrowserRouter as Router, Routes, Route, Link, useNavigate, useLocation } from 'react-router-dom';
import './App.css';

const API_URL = "https://proje-sifir.onrender.com"; // Canlı Sunucu

// --- GİRİŞ / KAYIT MODALI ---
function GirisModal({ kapali, kapat, tip }) { 
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [nickname, setNickname] = useState(""); const [code, setCode] = useState(""); 
  const [hata, setHata] = useState(""); const [bilgi, setBilgi] = useState(""); 
  const [kayitAsama, setKayitAsama] = useState(1);

  useEffect(() => { if(kapali) { setKayitAsama(1); setHata(""); setBilgi(""); setCode(""); } }, [kapali]);
  if (kapali) return null;

  const girisYap = async () => {
    setHata(""); setBilgi("");
    try { 
        const res = await fetch(`${API_URL}/giris`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({email, password}) }); 
        const data = await res.json(); 
        if (!data.success) setHata(data.error); 
        else { 
            setBilgi("✅ Giriş başarılı! Yönlendiriliyorsunuz...");
            localStorage.setItem('token', data.token); 
            localStorage.setItem('user', JSON.stringify(data.user)); 
            setTimeout(() => { window.location.reload(); kapat(); }, 1500);
        } 
    } catch(e) { setHata("Sunucuya bağlanılamadı."); }
  };

  const kodGonder = async () => { setHata(""); setBilgi("Kod gönderiliyor..."); try { const res = await fetch(`${API_URL}/kod-gonder`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({email}) }); const data = await res.json(); if (!data.success) { setHata(data.error); setBilgi(""); } else { setBilgi("Kod mailine gönderildi!"); setKayitAsama(2); } } catch(e) { setHata("Hata oluştu."); } };
  const kayitTamamla = async () => { setHata(""); setBilgi(""); try { const res = await fetch(`${API_URL}/kayit-tamamla`, { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({email, password, nickname, code}) }); const data = await res.json(); if (!data.success) setHata(data.error); else { setBilgi("Kayıt başarılı! Giriş yapılıyor..."); setTimeout(()=>{ kapat(); window.location.reload(); }, 1500); } } catch(e) { setHata("Hata oluştu."); } };

  return ( <div className="modal-overlay"> <div className="modal-box"> <button onClick={kapat} className="modal-close">✖</button> <h2 style={{ textAlign: 'center', color: '#004aad', marginTop: 0 }}>{tip === 'giris' ? 'Giriş Yap' : 'Kayıt Ol'}</h2> {hata && <div style={{background:'#ffebee', color:'#d32f2f', padding:10, borderRadius:8, marginBottom:10}}>{hata}</div>} {bilgi && <div style={{background:'#e8f5e9', color:'#2e7d32', padding:10, borderRadius:8, marginBottom:10}}>{bilgi}</div>}
  <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}> {tip === 'giris' ? ( <> <input type="email" placeholder="E-posta" value={email} onChange={e => setEmail(e.target.value)} className="modal-input" /> <input type="password" placeholder="Şifre" value={password} onChange={e => setPassword(e.target.value)} className="modal-input" /> <button onClick={girisYap} className="modal-btn">Giriş Yap</button> </> ) : ( kayitAsama === 1 ? ( <> <input type="email" placeholder="E-posta (@ogr.cu.edu.tr)" value={email} onChange={e => setEmail(e.target.value)} className="modal-input" /> <button onClick={kodGonder} className="modal-btn">Kod Gönder</button> </> ) : ( <> <input type="text" placeholder="Kod (123456)" value={code} onChange={e => setCode(e.target.value)} className="modal-input" style={{textAlign:'center', letterSpacing:5}} maxLength={6}/> <input type="text" placeholder="Takma Ad" value={nickname} onChange={e => setNickname(e.target.value)} className="modal-input" /> <input type="password" placeholder="Şifre Belirle" value={password} onChange={e => setPassword(e.target.value)} className="modal-input" /> <button onClick={kayitTamamla} className="modal-btn" style={{background:'#28a745'}}>Kayıt Ol</button> </> ) )} </div> </div> </div> );
}

// --- ADMIN PANELİ ---
const AdminPanel = () => {
    const [veriler, setVeriler] = useState({ ders: [], yurt: [], forum: [], mesajlar: [] });
    const veriCek = () => { fetch(`${API_URL}/admin/tum-veriler`).then(res => res.json()).then(data => setVeriler(data)).catch(()=>setVeriler({ders:[],yurt:[],forum:[],mesajlar:[]})); };
    useEffect(() => { veriCek(); }, []);
    const sil = (tur, id) => { if(!window.confirm("Sil?")) return; fetch(`${API_URL}/admin/sil/${tur}/${id}`, { method: 'DELETE' }).then(() => { veriCek(); }); };
    const banla = (nickname) => { if(!nickname || nickname === 'Anonim') return; if(window.confirm(`BANLA: ${nickname}?`)) { fetch(`${API_URL}/admin/banla`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ nickname }) }).then(() => alert("Banlandı!")); } };
    return ( <div style={{padding:40, maxWidth:1000, margin:'0 auto'}}> <h1 style={{color:'#d32f2f', textAlign:'center'}}>👑 Admin Paneli</h1> <div style={{textAlign:'center', marginBottom:30}}><Link to="/" style={{padding:'10px 20px', background:'#eee', borderRadius:5, textDecoration:'none', color:'#333', fontWeight:'bold'}}>Ana Sayfaya Dön</Link></div> <div style={{display:'grid', gridTemplateColumns:'1fr 1fr', gap:20}}> <div style={{background:'#fff', padding:15, border:'1px solid #ddd', borderRadius:8}}><h3>📨 Mesajlar</h3>{veriler.mesajlar.map(x=><div key={x.id} style={{borderBottom:'1px solid #eee', padding:'5px 0'}}><small>{x.mesaj}</small> <button onClick={()=>sil('mesaj',x.id)}>🗑️</button></div>)}</div> <div style={{background:'#fff', padding:15, border:'1px solid #ddd', borderRadius:8}}><h3>💬 Ders Yorumları</h3>{veriler.ders.map(x => (<div key={x.id} style={{borderBottom:'1px solid #eee', padding:'10px 0'}}><div style={{fontSize:'0.9em'}}><b>{x.kullanici_adi}</b>: {x.yorum_metni}</div><button onClick={()=>banla(x.kullanici_adi)}>🚫</button> <button onClick={()=>sil('ders',x.id)}>🗑️</button></div>))}</div> <div style={{background:'#fff', padding:15, border:'1px solid #ddd', borderRadius:8}}><h3>🛏️ Yurt Yorumları</h3>{veriler.yurt.map(x => (<div key={x.id} style={{borderBottom:'1px solid #eee', padding:'10px 0'}}><div style={{fontSize:'0.9em'}}><b>{x.kullanici_adi}</b>: {x.yorum_metni}</div><button onClick={()=>banla(x.kullanici_adi)}>🚫</button> <button onClick={()=>sil('yurt',x.id)}>🗑️</button></div>))}</div> <div style={{background:'#fff', padding:15, border:'1px solid #ddd', borderRadius:8}}><h3>🗣️ Forum</h3>{veriler.forum.map(x => (<div key={x.id} style={{borderBottom:'1px solid #eee', padding:'10px 0'}}><div style={{fontSize:'0.9em'}}><b>{x.kullanici_adi}</b>: {x.mesaj}</div><button onClick={()=>banla(x.kullanici_adi)}>🚫</button> <button onClick={()=>sil('forum',x.id)}>🗑️</button></div>))}</div> </div> </div> );
};

// --- ANA SAYFA ---
function AnaSayfa() {
  const navigate = useNavigate();
  const [iletisimAcik, setIletisimAcik] = useState(false);
  const [mesaj, setMesaj] = useState("");
  const [bilgi, setBilgi] = useState("");
  const [modalAcik, setModalAcik] = useState(false);
  const [modalTip, setModalTip] = useState('giris');
  const [kullanici, setKullanici] = useState(null);
  const [toplamYorum, setToplamYorum] = useState(0);
  const [mobilMenuAcik, setMobilMenuAcik] = useState(false);

  useEffect(() => { const u = localStorage.getItem('user'); if (u) setKullanici(JSON.parse(u)); fetch(`${API_URL}/toplam-yorum-sayisi`).then(r=>r.json()).then(d=>setToplamYorum(d.toplam)).catch(()=>{}); }, []);
  const cikisYap = () => { localStorage.removeItem('token'); localStorage.removeItem('user'); window.location.reload(); };
  const barYuzdesi = Math.min((toplamYorum / 600) * 100, 100);
  const mesajGonder = () => { if (!mesaj.trim()) return; fetch(`${API_URL}/iletisim-gonder`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ mesaj }) }).then(() => { setBilgi("İletildi!"); setMesaj(""); setTimeout(() => setIletisimAcik(false), 1500); }); };

  const menuler = [ {id:1,t:'Fakülteler',i:'🏛️',l:'/fakulteler'}, {id:2,t:'Hocalar',i:'👨‍🏫',l:'/hocalar'}, {id:3,t:'Anonim',i:'🎭',l:'/anonimler'}, {id:4,t:'Yurtlar',i:'🛏️',l:'/yurtlar'}, {id:5,t:'Sorular',i:'❓',l:'/sorular'}, {id:6,t:'Topluluklar',i:'🤝',l:'/topluluklar'} ];

  const MobilMenu = () => (
      <div className="mobile-menu-overlay" onClick={()=>setMobilMenuAcik(false)}>
          <div className="mobile-menu-content" onClick={e=>e.stopPropagation()}>
              <button className="close-menu" onClick={()=>setMobilMenuAcik(false)}>✖</button>
              <h3>Menü</h3>
              {kullanici?.nickname === 'baraykanat' && <div onClick={() => navigate('/admin')} className="menu-item" style={{background:'#FFD700'}}>👑 Admin</div>}
              {menuler.map(m=><div key={m.id} onClick={()=>{navigate(m.l);setMobilMenuAcik(false)}} className="menu-item"><span>{m.i}</span>{m.t}</div>)}
              <hr/>
              <p>İletişim</p>
              {!iletisimAcik ? <button onClick={()=>setIletisimAcik(true)} className="modal-btn">Mesaj Yaz</button> : <div><textarea style={{width:'90%'}} value={mesaj} onChange={e=>setMesaj(e.target.value)}/><button onClick={mesajGonder} className="modal-btn">Gönder</button></div>}
          </div>
      </div>
  );

  return (
    <div style={{ padding: '30px', maxWidth: '1100px', margin: '0 auto', minHeight: '85vh', display: 'flex', flexDirection: 'column' }}>
      <div style={{position: 'fixed', bottom: '10px', left: '15px', color: '#ccc', fontSize: '12px'}}>Beta 0.32</div>
      <GirisModal kapali={!modalAcik} kapat={() => setModalAcik(false)} tip={modalTip} />
      
      <div className="mobile-header"> <button className="hamburger-btn" onClick={()=>setMobilMenuAcik(true)}>☰</button> <h1 style={{margin:0, color:'#004aad'}}>Çukurova Kampüs</h1> </div>
      {mobilMenuAcik && <MobilMenu/>}

      <header className="desktop-header" style={{ textAlign: 'center', marginBottom: '40px' }}> <h1 style={{ color: '#004aad', fontSize: '38px', margin: '0 0 8px 0', fontWeight: '800' }}>Çukurova Kampüs</h1> <p style={{ color: '#666', fontSize: '16px', margin: 0 }}>Öğrenci Yorum ve Bilgi Platformu</p> </header>

      <div className="content-grid" style={{ display: 'flex', gap: '30px', alignItems: 'flex-start', justifyContent: 'space-between' }}>
        {/* SOL */}
        <div className="left-col desktop-only" style={{ flex: '1', minWidth: '220px' }}> <h3 style={{ borderBottom:'1px solid #ddd' }}>Menü</h3> {kullanici?.nickname === 'baraykanat' && <div onClick={() => navigate('/admin')} style={{ background: '#FFD700', padding: 12, borderRadius: 8, cursor: 'pointer', fontWeight: 'bold', textAlign:'center', marginBottom:10 }}>👑 Admin</div>} <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}> {menuler.map(m=><div key={m.id} onClick={()=>navigate(m.l)} style={{background:'white', padding:15, borderRadius:8, cursor:'pointer', boxShadow:'0 2px 4px rgba(0,0,0,0.05)', display:'flex', alignItems:'center', border:'1px solid #eee'}}><span style={{marginRight:12, fontSize:18}}>{m.i}</span>{m.t}</div>)} </div> </div>
        
        {/* ORTA */}
        <div className="center-col" style={{ flex: '1.5', minWidth: '280px', backgroundColor: 'white', padding: '40px 30px', borderRadius: '12px', textAlign: 'center', boxShadow: '0 5px 20px rgba(0,0,0,0.06)', border: '1px solid #e0e0e0' }}> 
            {!kullanici ? (<> <h2 style={{ color: '#004aad', fontSize: '26px', margin: '0 0 15px 0' }}>Hoş Geldin</h2> <p style={{ color: '#555', marginBottom: '30px' }}>Yorum yapmak için giriş yapmalısın.</p> <div style={{display:'flex', flexDirection:'column', gap:12, maxWidth:220, margin:'0 auto'}}> <button onClick={()=>{setModalTip('giris');setModalAcik(true)}} className="modal-btn">Giriş Yap</button> <button onClick={()=>{setModalTip('kayit');setModalAcik(true)}} style={{padding:12, background:'white', color:'#004aad', border:'2px solid #004aad', borderRadius:8, cursor:'pointer', fontWeight:'bold'}}>Kayıt Ol</button> </div> </>) : (<> <h2 style={{ color: '#004aad', fontSize: '26px', margin: '0 0 10px 0' }}>{kullanici.nickname}</h2> <p style={{ color: '#555', marginBottom: '30px' }}>Giriş yaptın.</p> <button onClick={cikisYap} style={{ padding:'12px 30px', background:'#ff4444', color:'white', border:'none', borderRadius:8, cursor:'pointer', fontWeight:'bold' }}>Çıkış Yap</button> </>)}
            <div style={{ marginTop: 40, paddingTop: 20, borderTop: '1px solid #eee' }}> <p style={{ fontSize: 13, color: '#004aad', fontWeight: 'bold', marginBottom: 10 }}>2025 Sonuna kadar her 600 yorum için<br/>Darüşşafaka'ya 200 TL Bağış!</p> <div style={{ width: '100%', height: 15, background: '#eee', borderRadius: 10, overflow: 'hidden' }}> <div style={{ width: `${barYuzdesi}%`, height: '100%', background: '#2ecc71', transition: 'width 0.5s' }}></div> </div> <small style={{ color: '#777' }}>{toplamYorum} / 600 Yorum</small> </div>
        </div>

        {/* SAĞ */}
        <div className="right-col desktop-only" style={{ flex: '1', minWidth: '220px' }}> <h3 style={{ borderBottom:'1px solid #ddd' }}>İletişim</h3> <div style={{ backgroundColor: '#fff', padding: '20px', borderRadius: '12px', border: '1px solid #eee', boxShadow: '0 2px 4px rgba(0,0,0,0.05)' }}> <p style={{ fontSize: '14px', color: '#555' }}>Öneri ve şikayetleriniz:</p> {!iletisimAcik ? <button onClick={()=>setIletisimAcik(true)} className="modal-btn" style={{background:'#f0f0f0', color:'#333', border:'1px solid #ccc'}}>Mesaj Yaz</button> : <div><textarea rows="4" value={mesaj} onChange={e=>setMesaj(e.target.value)} style={{width:'90%', padding:10}}/><button onClick={mesajGonder} className="modal-btn" style={{background:'green'}}>Gönder</button></div>} {bilgi && <div style={{color:'green', marginTop:5}}>{bilgi}</div>} <div style={{marginTop:15, textAlign:'center', borderTop:'1px solid #eee', paddingTop:10}}><a href="mailto:cukampus2025@gmail.com" style={{color:'#004aad', fontWeight:'bold', textDecoration:'none'}}>📧 Mail At</a></div> </div> </div>
      </div>
    </div>
  );
}

// --- İÇERİK SAYFALARI ---
const Topluluklar = () => ( <div style={{padding:40,textAlign:'center'}}><h1>Topluluklar</h1><p>İletişime geçin ekleyelim.</p><Link to="/">Geri</Link></div> );
const BosSayfa = ({baslik}) => <div style={{padding:20}}><Link to="/">⬅️ Geri</Link><h2>{baslik}</h2><p>Yapım aşamasında...</p></div>;
function ForumSayfasi({ tur, baslik, anonimMi }) { const navigate = useNavigate(); const [gonderiler, setGonderiler] = useState([]); const [yeniMesaj, setYeniMesaj] = useState(""); const [cevapKutusuAcik, setCevapKutusuAcik] = useState(null); const [cevapMesaj, setCevapMesaj] = useState(""); const [kullanici, setKullanici] = useState(null); const verileriCek = useCallback(() => { fetch(`${API_URL}/forum/${tur}`).then(res => res.json()).then(data => { if(Array.isArray(data)) setGonderiler(data); else setGonderiler([]); }).catch(()=>setGonderiler([])); }, [tur]); useEffect(() => { const user = localStorage.getItem('user'); if (user) setKullanici(JSON.parse(user)); verileriCek(); }, [verileriCek, tur]); const gonder = (ustId = 0, mesajIcerik) => { if (!mesajIcerik.trim()) return; const ad = anonimMi ? 'Anonim' : (kullanici ? kullanici.nickname : 'Misafir'); fetch(`${API_URL}/forum-ekle`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ tur, ust_id: ustId, kullanici_adi: ad, mesaj: mesajIcerik }) }).then(() => { setYeniMesaj(""); setCevapMesaj(""); setCevapKutusuAcik(null); verileriCek(); }); }; const kendiYorumunuSil = (id) => { if(window.confirm("Silmek istiyor musun?")) fetch(`${API_URL}/yorum-sil`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({tur:'forum', id, kullanici_adi:kullanici.nickname})}).then(()=>{verileriCek();}); }; if (!kullanici) { return ( <div style={{ padding: '40px', textAlign: 'center', height: '80vh' }}><div style={{ filter: 'blur(8px)' }}><h2>{baslik}</h2></div><div style={{ position: 'absolute', top: '50%', left: '50%', transform: 'translate(-50%, -50%)', background: 'white', padding: '40px', borderRadius: '20px', border: '1px solid #eee' }}><h2 style={{color:'#004aad'}}>🔒 Giriş Yap</h2><button onClick={() => navigate('/')} style={{padding: '10px 20px', background:'#004aad', color:'white'}}>Giriş</button></div></div> ); } return ( <div style={{ padding: 20, maxWidth: 800, margin: '0 auto' }}> <button onClick={()=>navigate('/')}>⬅️</button> <h2>{baslik}</h2> <textarea value={yeniMesaj} onChange={(e)=>setYeniMesaj(e.target.value)} style={{width:'95%', padding:10}}/><button onClick={()=>gonder(0, yeniMesaj)} style={{marginTop:10, padding:10, background:'#004aad', color:'white'}}>Paylaş</button> <div style={{marginTop:20}}>{gonderiler.map(s=><div key={s.id} style={{padding:15, border:'1px solid #eee', marginBottom:10}}><b>{anonimMi?'Anonim':s.kullanici_adi}</b>: {s.mesaj} {kullanici.nickname===s.kullanici_adi && <button onClick={()=>kendiYorumunuSil(s.id)}>🗑️</button>} </div>)}</div> </div> ); }
function YurtlarSayfasi() { const navigate = useNavigate(); const [seciliYurt, setSeciliYurt] = useState(null); const [yorumlar, setYorumlar] = useState([]); const [yeniYorum, setYeniYorum] = useState(""); const [kullanici, setKullanici] = useState(null); const yurtListesi = ["Beş Ocak Kyk", "Toroslar Kyk", "Fevzi Çakmak Kyk", "Mahmut Sami Ramazanoğlu Kyk", "Ceyhan Kyk", "Kozan Kyk", "Çukurova Kyk", "Adana Kyk", "Kutul Amare Kyk"]; useEffect(() => { const user = localStorage.getItem('user'); if (user) setKullanici(JSON.parse(user)); }, []); const yurtSec = (yurt) => { setSeciliYurt(yurt); fetch(`${API_URL}/yurt-yorumlari/${yurt}`).then(res => res.json()).then(data => { if(Array.isArray(data)) setYorumlar(data); else setYorumlar([]); }).catch(()=>setYorumlar([])); }; const yorumGonder = () => { if (!yeniYorum.trim()) return; fetch(`${API_URL}/yurt-yorum-ekle`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ yurt_adi: seciliYurt, yorum_metni: yeniYorum, kullanici_adi: kullanici.nickname }) }).then(() => { setYeniYorum(""); yurtSec(seciliYurt); }); }; const kendiYorumunuSil = (id) => { if(window.confirm("Sil?")) fetch(`${API_URL}/yorum-sil`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({tur:'yurt', id, kullanici_adi:kullanici.nickname})}).then(()=>{yurtSec(seciliYurt);}); }; return ( <div style={{ padding: 20, maxWidth: 800, margin: '0 auto' }}> <button onClick={()=>seciliYurt?setSeciliYurt(null):navigate('/')}>⬅️</button> <h2>{seciliYurt||'Yurtlar'}</h2> {!seciliYurt ? yurtListesi.map(y=><div key={y} onClick={()=>yurtSec(y)} style={{padding:15, border:'1px solid #eee', cursor:'pointer'}}>{y}</div>) : (kullanici ? <div><textarea value={yeniYorum} onChange={e=>setYeniYorum(e.target.value)} style={{width:'95%'}}/><button onClick={yorumGonder} style={{marginTop:10}}>Gönder</button> {yorumlar.map(y=><div key={y.id} style={{borderBottom:'1px solid #eee', padding:10}}><b>{y.kullanici_adi}</b>: {y.yorum_metni} {kullanici.nickname===y.kullanici_adi && <button onClick={()=>kendiYorumunuSil(y.id)}>🗑️</button>}</div>)} </div> : <div>🔒 Giriş Yap</div>)} </div> ); }
function DersDetay() { const location = useLocation(); const navigate = useNavigate(); const ders = location.state?.ders; const [kullanici, setKullanici] = useState(null); const [yeniYorum, setYeniYorum] = useState(""); const [yorumlar, setYorumlar] = useState([]); const verileriGuncelle = useCallback(() => { if(ders) { fetch(`${API_URL}/ders-yorumlari/${ders.ders_kodu}`).then(res => res.json()).then(data => { if(Array.isArray(data)) setYorumlar(data); else setYorumlar([]); }).catch(()=>setYorumlar([])); } }, [ders]); useEffect(() => { const user = localStorage.getItem('user'); if (user) setKullanici(JSON.parse(user)); verileriGuncelle(); }, [ders, verileriGuncelle]); const yorumGonder = () => { if (!yeniYorum.trim()) return; fetch(`${API_URL}/ders-yorum-ekle`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ders_kodu: ders.ders_kodu, ders_adi: ders.ders_adi, kullanici_adi: kullanici.nickname, yorum_metni: yeniYorum }) }).then(() => { setYeniYorum(""); verileriGuncelle(); }); }; const kendiYorumunuSil = (id) => { if(window.confirm("Sil?")) fetch(`${API_URL}/yorum-sil`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({tur:'ders', id, kullanici_adi:kullanici.nickname})}).then(()=>{verileriGuncelle();}); }; if(!ders) return <div>Hata</div>; return <div style={{padding:20, maxWidth:800, margin:'0 auto'}}> <button onClick={()=>navigate(-1)}>⬅️</button> <h2>{ders.ders_adi}</h2> <p>{ders.hoca_adi}</p> {kullanici ? <div><textarea value={yeniYorum} onChange={e=>setYeniYorum(e.target.value)} style={{width:'95%'}}/><button onClick={yorumGonder} style={{marginTop:10}}>Yorum Yap</button> {yorumlar.map(y=><div key={y.id} style={{borderBottom:'1px solid #eee', padding:10}}><b>{y.kullanici_adi}</b>: {y.yorum_metni} {kullanici.nickname===y.kullanici_adi && <button onClick={()=>kendiYorumunuSil(y.id)}>🗑️</button>}</div>)} </div> : <div>🔒 Giriş Yap</div>} </div>; }
function FakultelerSayfasi() { const [data, setData] = useState([]); const [fak, setFak] = useState(null); const [bol, setBol] = useState(null); const [dersler, setDersler] = useState([]); const [arama, setArama] = useState(""); const nav = useNavigate(); useEffect(() => { fetch(`${API_URL}/bolumler`).then(res => res.json()).then(data => setData(data)); }, []); const fList = [...new Set(data.map(i=>i.fakulte))].filter(x=>x.includes(arama)); const bList = data.filter(x=>x.fakulte===fak && x.bolum.includes(arama)); const dList = dersler.filter(d=>d.ders_adi.includes(arama)); const don = () => { setArama(""); if(bol) setBol(null); else if(fak) setFak(null); else nav('/'); }; return <div style={{padding:20, maxWidth:800, margin:'0 auto'}}><div style={{display:'flex', alignItems:'center'}}><button onClick={don}>⬅️</button><h2>Seçim</h2></div><input value={arama} onChange={e=>setArama(e.target.value)} placeholder="Ara..." style={{width:'95%', padding:10, marginBottom:10}}/> {!fak ? fList.map((x,i)=><div key={i} onClick={()=>setFak(x)} style={{padding:15, border:'1px solid #eee'}}>{x}</div>) : !bol ? bList.map((x,i)=><div key={i} onClick={()=>{setBol(x.bolum); fetch(`${API_URL}/dersler/${x.bolum}`).then(r=>r.json()).then(d=>setDersler(d))}} style={{padding:15, border:'1px solid #eee'}}>{x.bolum}</div>) : dList.map(d=><div key={d.id} onClick={()=>nav('/ders-detay',{state:{ders:d}})} style={{padding:15, border:'1px solid #eee'}}>{d.ders_adi}</div>)} </div>; }
function HocalarSayfasi() { const [data, setData] = useState([]); const [arama, setArama] = useState(""); const [secili, setSecili] = useState(null); const [dersler, setDersler] = useState([]); const nav = useNavigate(); useEffect(() => { fetch(`${API_URL}/hocalar`).then(res => res.json()).then(data => { if(Array.isArray(data)) setData(data); }); }, []); const hocaSec = (h) => { setSecili(h); fetch(`${API_URL}/hoca-dersleri/${h}`).then(r=>r.json()).then(d=>setDersler(d)); }; const don = () => { if(secili) setSecili(null); else nav('/'); }; const filtreli = data.filter(i=>i.hoca_adi && i.hoca_adi.toLowerCase().includes(arama.toLowerCase())); return <div style={{padding:20, maxWidth:800, margin:'0 auto'}}><div style={{display:'flex', alignItems:'center'}}><button onClick={don}>⬅️</button><h2>Hoca Bul</h2></div>{!secili ? <div><input value={arama} onChange={e=>setArama(e.target.value)} placeholder="Hoca ara..." style={{width:'95%', padding:10}}/>{filtreli.slice(0,30).map((x,i)=><div key={i} onClick={()=>hocaSec(x.hoca_adi)} style={{padding:15, border:'1px solid #eee'}}>{x.hoca_adi}</div>)}</div> : <div><h3>{secili} Dersleri:</h3>{dersler.map(d=><div key={d.id} onClick={()=>nav('/ders-detay',{state:{ders:d}})} style={{padding:15, border:'1px solid #eee'}}>{d.ders_adi}</div>)}</div>}</div>; }

function App() { return ( <Router> <Routes> <Route path="/" element={<AnaSayfa />} /> <Route path="/fakulteler" element={<FakultelerSayfasi />} /> <Route path="/hocalar" element={<HocalarSayfasi />} /> <Route path="/ders-detay" element={<DersDetay />} /> <Route path="/sorular" element={<ForumSayfasi tur="soru" baslik="❓ Soru - Cevap" />} /> <Route path="/anonimler" element={<ForumSayfasi tur="anonim" baslik="🎭 Burada Anonimsin" anonimMi={true} />} /> <Route path="/yurtlar" element={<YurtlarSayfasi />} /> <Route path="/topluluklar" element={<Topluluklar />} /> <Route path="/tavsiyeler" element={<BosSayfa baslik="Tavsiyeler" />} /> <Route path="/admin" element={<AdminPanel />} /> </Routes> </Router> ); }

export default App;